package com.itertk.app.mpos.locationhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table aircities.
 */
public class AirCity {

    /** Not-null value. */
    private String code;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String py;
    /** Not-null value. */
    private String pyzm;
    private int count;

    public AirCity() {
    }

    public AirCity(String name) {
        this.name = name;
    }

    public AirCity(String code, String name, String py, String pyzm, int count) {
        this.code = code;
        this.name = name;
        this.py = py;
        this.pyzm = pyzm;
        this.count = count;
    }

    /** Not-null value. */
    public String getCode() {
        return code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCode(String code) {
        this.code = code;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPy() {
        return py;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPy(String py) {
        this.py = py;
    }

    /** Not-null value. */
    public String getPyzm() {
        return pyzm;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPyzm(String pyzm) {
        this.pyzm = pyzm;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

}
