package com.itertk.app.mpos.locationhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table bank.
 */
public class Bank {

    private Long code;
    /** Not-null value. */
    private String name;

    public Bank() {
    }

    public Bank(Long code) {
        this.code = code;
    }

    public Bank(Long code, String name) {
        this.code = code;
        this.name = name;
    }

    public Long getCode() {
        return code;
    }

    public void setCode(Long code) {
        this.code = code;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

}
