package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ADDRESS.
 */
public class Address {

    private Long addr_id;
    private String address1;
    private boolean moren;

    public Address() {
    }

    public Address(Long addr_id) {
        this.addr_id = addr_id;
    }

    public Address(Long addr_id, String address1, boolean moren) {
        this.addr_id = addr_id;
        this.address1 = address1;
        this.moren = moren;
    }

    public Long getAddr_id() {
        return addr_id;
    }

    public void setAddr_id(Long addr_id) {
        this.addr_id = addr_id;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public boolean getMoren() {
        return moren;
    }

    public void setMoren(boolean moren) {
        this.moren = moren;
    }

}
