package com.itertk.app.mpos.dbhelper;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.itertk.app.mpos.dbhelper.AttributeValue;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ATTRIBUTE_VALUE.
*/
public class AttributeValueDao extends AbstractDao<AttributeValue, Long> {

    public static final String TABLENAME = "ATTRIBUTE_VALUE";

    /**
     * Properties of entity AttributeValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ValueId = new Property(0, Long.class, "valueId", true, "VALUE_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property PriceAddition = new Property(2, String.class, "priceAddition", false, "PRICE_ADDITION");
        public final static Property AttributeId = new Property(3, long.class, "attributeId", false, "ATTRIBUTE_ID");
    };

    private DaoSession daoSession;

    private Query<AttributeValue> attribute_AttributeValueListQuery;

    public AttributeValueDao(DaoConfig config) {
        super(config);
    }
    
    public AttributeValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ATTRIBUTE_VALUE' (" + //
                "'VALUE_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: valueId
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'PRICE_ADDITION' TEXT NOT NULL ," + // 2: priceAddition
                "'ATTRIBUTE_ID' INTEGER NOT NULL );"); // 3: attributeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ATTRIBUTE_VALUE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AttributeValue entity) {
        stmt.clearBindings();
 
        Long valueId = entity.getValueId();
        if (valueId != null) {
            stmt.bindLong(1, valueId);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getPriceAddition());
        stmt.bindLong(4, entity.getAttributeId());
    }

    @Override
    protected void attachEntity(AttributeValue entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AttributeValue readEntity(Cursor cursor, int offset) {
        AttributeValue entity = new AttributeValue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // valueId
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // priceAddition
            cursor.getLong(offset + 3) // attributeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AttributeValue entity, int offset) {
        entity.setValueId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setPriceAddition(cursor.getString(offset + 2));
        entity.setAttributeId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AttributeValue entity, long rowId) {
        entity.setValueId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AttributeValue entity) {
        if(entity != null) {
            return entity.getValueId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "attributeValueList" to-many relationship of Attribute. */
    public List<AttributeValue> _queryAttribute_AttributeValueList(long attributeId) {
        synchronized (this) {
            if (attribute_AttributeValueListQuery == null) {
                QueryBuilder<AttributeValue> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AttributeId.eq(null));
                attribute_AttributeValueListQuery = queryBuilder.build();
            }
        }
        Query<AttributeValue> query = attribute_AttributeValueListQuery.forCurrentThread();
        query.setParameter(0, attributeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAttributeDao().getAllColumns());
            builder.append(" FROM ATTRIBUTE_VALUE T");
            builder.append(" LEFT JOIN ATTRIBUTE T0 ON T.'ATTRIBUTE_ID'=T0.'ATTRIBUTE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected AttributeValue loadCurrentDeep(Cursor cursor, boolean lock) {
        AttributeValue entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Attribute attribute = loadCurrentOther(daoSession.getAttributeDao(), cursor, offset);
         if(attribute != null) {
            entity.setAttribute(attribute);
        }

        return entity;    
    }

    public AttributeValue loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<AttributeValue> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<AttributeValue> list = new ArrayList<AttributeValue>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<AttributeValue> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<AttributeValue> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
