package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP.
 */
public class Backup {

    private Long backupId;
    /** Not-null value. */
    private String name;
    private long last_update;

    public Backup() {
    }

    public Backup(Long backupId) {
        this.backupId = backupId;
    }

    public Backup(Long backupId, String name, long last_update) {
        this.backupId = backupId;
        this.name = name;
        this.last_update = last_update;
    }

    public Long getBackupId() {
        return backupId;
    }

    public void setBackupId(Long backupId) {
        this.backupId = backupId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public long getLast_update() {
        return last_update;
    }

    public void setLast_update(long last_update) {
        this.last_update = last_update;
    }

}
