package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BANKCARD.
 */
public class Bankcard {

    private Long bankcardId;
    /** Not-null value. */
    private String bankcardNo;
    /** Not-null value. */
    private String cardOwnerName;

    public Bankcard() {
    }

    public Bankcard(Long bankcardId) {
        this.bankcardId = bankcardId;
    }

    public Bankcard(Long bankcardId, String bankcardNo, String cardOwnerName) {
        this.bankcardId = bankcardId;
        this.bankcardNo = bankcardNo;
        this.cardOwnerName = cardOwnerName;
    }

    public Long getBankcardId() {
        return bankcardId;
    }

    public void setBankcardId(Long bankcardId) {
        this.bankcardId = bankcardId;
    }

    /** Not-null value. */
    public String getBankcardNo() {
        return bankcardNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBankcardNo(String bankcardNo) {
        this.bankcardNo = bankcardNo;
    }

    /** Not-null value. */
    public String getCardOwnerName() {
        return cardOwnerName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCardOwnerName(String cardOwnerName) {
        this.cardOwnerName = cardOwnerName;
    }

}
