package com.itertk.app.mpos.dbhelper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.itertk.app.mpos.dbhelper.Shop;
import com.itertk.app.mpos.dbhelper.System;
import com.itertk.app.mpos.dbhelper.Backup;
import com.itertk.app.mpos.dbhelper.User;
import com.itertk.app.mpos.dbhelper.Bankcard;
import com.itertk.app.mpos.dbhelper.Catalog;
import com.itertk.app.mpos.dbhelper.Product;
import com.itertk.app.mpos.dbhelper.Retail;
import com.itertk.app.mpos.dbhelper.Reduce;
import com.itertk.app.mpos.dbhelper.Attribute;
import com.itertk.app.mpos.dbhelper.AttributeValue;
import com.itertk.app.mpos.dbhelper.ProductAttribute;
import com.itertk.app.mpos.dbhelper.SaleOrder;
import com.itertk.app.mpos.dbhelper.SaleOrderReduce;
import com.itertk.app.mpos.dbhelper.SaleOrderItem;
import com.itertk.app.mpos.dbhelper.SaleOrderItemAttributeValue;
import com.itertk.app.mpos.dbhelper.SaleOrderItemReduce;
import com.itertk.app.mpos.dbhelper.Cart;
import com.itertk.app.mpos.dbhelper.CartItem;
import com.itertk.app.mpos.dbhelper.ShopOrder;
import com.itertk.app.mpos.dbhelper.ShopOrderItem;
import com.itertk.app.mpos.dbhelper.Advertising;
import com.itertk.app.mpos.dbhelper.Permission;
import com.itertk.app.mpos.dbhelper.Address;
import com.itertk.app.mpos.dbhelper.GpsLocation;

import com.itertk.app.mpos.dbhelper.ShopDao;
import com.itertk.app.mpos.dbhelper.SystemDao;
import com.itertk.app.mpos.dbhelper.BackupDao;
import com.itertk.app.mpos.dbhelper.UserDao;
import com.itertk.app.mpos.dbhelper.BankcardDao;
import com.itertk.app.mpos.dbhelper.CatalogDao;
import com.itertk.app.mpos.dbhelper.ProductDao;
import com.itertk.app.mpos.dbhelper.RetailDao;
import com.itertk.app.mpos.dbhelper.ReduceDao;
import com.itertk.app.mpos.dbhelper.AttributeDao;
import com.itertk.app.mpos.dbhelper.AttributeValueDao;
import com.itertk.app.mpos.dbhelper.ProductAttributeDao;
import com.itertk.app.mpos.dbhelper.SaleOrderDao;
import com.itertk.app.mpos.dbhelper.SaleOrderReduceDao;
import com.itertk.app.mpos.dbhelper.SaleOrderItemDao;
import com.itertk.app.mpos.dbhelper.SaleOrderItemAttributeValueDao;
import com.itertk.app.mpos.dbhelper.SaleOrderItemReduceDao;
import com.itertk.app.mpos.dbhelper.CartDao;
import com.itertk.app.mpos.dbhelper.CartItemDao;
import com.itertk.app.mpos.dbhelper.ShopOrderDao;
import com.itertk.app.mpos.dbhelper.ShopOrderItemDao;
import com.itertk.app.mpos.dbhelper.AdvertisingDao;
import com.itertk.app.mpos.dbhelper.PermissionDao;
import com.itertk.app.mpos.dbhelper.AddressDao;
import com.itertk.app.mpos.dbhelper.GpsLocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopDaoConfig;
    private final DaoConfig systemDaoConfig;
    private final DaoConfig backupDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig bankcardDaoConfig;
    private final DaoConfig catalogDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig retailDaoConfig;
    private final DaoConfig reduceDaoConfig;
    private final DaoConfig attributeDaoConfig;
    private final DaoConfig attributeValueDaoConfig;
    private final DaoConfig productAttributeDaoConfig;
    private final DaoConfig saleOrderDaoConfig;
    private final DaoConfig saleOrderReduceDaoConfig;
    private final DaoConfig saleOrderItemDaoConfig;
    private final DaoConfig saleOrderItemAttributeValueDaoConfig;
    private final DaoConfig saleOrderItemReduceDaoConfig;
    private final DaoConfig cartDaoConfig;
    private final DaoConfig cartItemDaoConfig;
    private final DaoConfig shopOrderDaoConfig;
    private final DaoConfig shopOrderItemDaoConfig;
    private final DaoConfig advertisingDaoConfig;
    private final DaoConfig permissionDaoConfig;
    private final DaoConfig addressDaoConfig;
    private final DaoConfig gpsLocationDaoConfig;

    private final ShopDao shopDao;
    private final SystemDao systemDao;
    private final BackupDao backupDao;
    private final UserDao userDao;
    private final BankcardDao bankcardDao;
    private final CatalogDao catalogDao;
    private final ProductDao productDao;
    private final RetailDao retailDao;
    private final ReduceDao reduceDao;
    private final AttributeDao attributeDao;
    private final AttributeValueDao attributeValueDao;
    private final ProductAttributeDao productAttributeDao;
    private final SaleOrderDao saleOrderDao;
    private final SaleOrderReduceDao saleOrderReduceDao;
    private final SaleOrderItemDao saleOrderItemDao;
    private final SaleOrderItemAttributeValueDao saleOrderItemAttributeValueDao;
    private final SaleOrderItemReduceDao saleOrderItemReduceDao;
    private final CartDao cartDao;
    private final CartItemDao cartItemDao;
    private final ShopOrderDao shopOrderDao;
    private final ShopOrderItemDao shopOrderItemDao;
    private final AdvertisingDao advertisingDao;
    private final PermissionDao permissionDao;
    private final AddressDao addressDao;
    private final GpsLocationDao gpsLocationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        systemDaoConfig = daoConfigMap.get(SystemDao.class).clone();
        systemDaoConfig.initIdentityScope(type);

        backupDaoConfig = daoConfigMap.get(BackupDao.class).clone();
        backupDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        bankcardDaoConfig = daoConfigMap.get(BankcardDao.class).clone();
        bankcardDaoConfig.initIdentityScope(type);

        catalogDaoConfig = daoConfigMap.get(CatalogDao.class).clone();
        catalogDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        retailDaoConfig = daoConfigMap.get(RetailDao.class).clone();
        retailDaoConfig.initIdentityScope(type);

        reduceDaoConfig = daoConfigMap.get(ReduceDao.class).clone();
        reduceDaoConfig.initIdentityScope(type);

        attributeDaoConfig = daoConfigMap.get(AttributeDao.class).clone();
        attributeDaoConfig.initIdentityScope(type);

        attributeValueDaoConfig = daoConfigMap.get(AttributeValueDao.class).clone();
        attributeValueDaoConfig.initIdentityScope(type);

        productAttributeDaoConfig = daoConfigMap.get(ProductAttributeDao.class).clone();
        productAttributeDaoConfig.initIdentityScope(type);

        saleOrderDaoConfig = daoConfigMap.get(SaleOrderDao.class).clone();
        saleOrderDaoConfig.initIdentityScope(type);

        saleOrderReduceDaoConfig = daoConfigMap.get(SaleOrderReduceDao.class).clone();
        saleOrderReduceDaoConfig.initIdentityScope(type);

        saleOrderItemDaoConfig = daoConfigMap.get(SaleOrderItemDao.class).clone();
        saleOrderItemDaoConfig.initIdentityScope(type);

        saleOrderItemAttributeValueDaoConfig = daoConfigMap.get(SaleOrderItemAttributeValueDao.class).clone();
        saleOrderItemAttributeValueDaoConfig.initIdentityScope(type);

        saleOrderItemReduceDaoConfig = daoConfigMap.get(SaleOrderItemReduceDao.class).clone();
        saleOrderItemReduceDaoConfig.initIdentityScope(type);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        cartItemDaoConfig = daoConfigMap.get(CartItemDao.class).clone();
        cartItemDaoConfig.initIdentityScope(type);

        shopOrderDaoConfig = daoConfigMap.get(ShopOrderDao.class).clone();
        shopOrderDaoConfig.initIdentityScope(type);

        shopOrderItemDaoConfig = daoConfigMap.get(ShopOrderItemDao.class).clone();
        shopOrderItemDaoConfig.initIdentityScope(type);

        advertisingDaoConfig = daoConfigMap.get(AdvertisingDao.class).clone();
        advertisingDaoConfig.initIdentityScope(type);

        permissionDaoConfig = daoConfigMap.get(PermissionDao.class).clone();
        permissionDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        gpsLocationDaoConfig = daoConfigMap.get(GpsLocationDao.class).clone();
        gpsLocationDaoConfig.initIdentityScope(type);

        shopDao = new ShopDao(shopDaoConfig, this);
        systemDao = new SystemDao(systemDaoConfig, this);
        backupDao = new BackupDao(backupDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        bankcardDao = new BankcardDao(bankcardDaoConfig, this);
        catalogDao = new CatalogDao(catalogDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        retailDao = new RetailDao(retailDaoConfig, this);
        reduceDao = new ReduceDao(reduceDaoConfig, this);
        attributeDao = new AttributeDao(attributeDaoConfig, this);
        attributeValueDao = new AttributeValueDao(attributeValueDaoConfig, this);
        productAttributeDao = new ProductAttributeDao(productAttributeDaoConfig, this);
        saleOrderDao = new SaleOrderDao(saleOrderDaoConfig, this);
        saleOrderReduceDao = new SaleOrderReduceDao(saleOrderReduceDaoConfig, this);
        saleOrderItemDao = new SaleOrderItemDao(saleOrderItemDaoConfig, this);
        saleOrderItemAttributeValueDao = new SaleOrderItemAttributeValueDao(saleOrderItemAttributeValueDaoConfig, this);
        saleOrderItemReduceDao = new SaleOrderItemReduceDao(saleOrderItemReduceDaoConfig, this);
        cartDao = new CartDao(cartDaoConfig, this);
        cartItemDao = new CartItemDao(cartItemDaoConfig, this);
        shopOrderDao = new ShopOrderDao(shopOrderDaoConfig, this);
        shopOrderItemDao = new ShopOrderItemDao(shopOrderItemDaoConfig, this);
        advertisingDao = new AdvertisingDao(advertisingDaoConfig, this);
        permissionDao = new PermissionDao(permissionDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);
        gpsLocationDao = new GpsLocationDao(gpsLocationDaoConfig, this);

        registerDao(Shop.class, shopDao);
        registerDao(System.class, systemDao);
        registerDao(Backup.class, backupDao);
        registerDao(User.class, userDao);
        registerDao(Bankcard.class, bankcardDao);
        registerDao(Catalog.class, catalogDao);
        registerDao(Product.class, productDao);
        registerDao(Retail.class, retailDao);
        registerDao(Reduce.class, reduceDao);
        registerDao(Attribute.class, attributeDao);
        registerDao(AttributeValue.class, attributeValueDao);
        registerDao(ProductAttribute.class, productAttributeDao);
        registerDao(SaleOrder.class, saleOrderDao);
        registerDao(SaleOrderReduce.class, saleOrderReduceDao);
        registerDao(SaleOrderItem.class, saleOrderItemDao);
        registerDao(SaleOrderItemAttributeValue.class, saleOrderItemAttributeValueDao);
        registerDao(SaleOrderItemReduce.class, saleOrderItemReduceDao);
        registerDao(Cart.class, cartDao);
        registerDao(CartItem.class, cartItemDao);
        registerDao(ShopOrder.class, shopOrderDao);
        registerDao(ShopOrderItem.class, shopOrderItemDao);
        registerDao(Advertising.class, advertisingDao);
        registerDao(Permission.class, permissionDao);
        registerDao(Address.class, addressDao);
        registerDao(GpsLocation.class, gpsLocationDao);
    }
    
    public void clear() {
        shopDaoConfig.getIdentityScope().clear();
        systemDaoConfig.getIdentityScope().clear();
        backupDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        bankcardDaoConfig.getIdentityScope().clear();
        catalogDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        retailDaoConfig.getIdentityScope().clear();
        reduceDaoConfig.getIdentityScope().clear();
        attributeDaoConfig.getIdentityScope().clear();
        attributeValueDaoConfig.getIdentityScope().clear();
        productAttributeDaoConfig.getIdentityScope().clear();
        saleOrderDaoConfig.getIdentityScope().clear();
        saleOrderReduceDaoConfig.getIdentityScope().clear();
        saleOrderItemDaoConfig.getIdentityScope().clear();
        saleOrderItemAttributeValueDaoConfig.getIdentityScope().clear();
        saleOrderItemReduceDaoConfig.getIdentityScope().clear();
        cartDaoConfig.getIdentityScope().clear();
        cartItemDaoConfig.getIdentityScope().clear();
        shopOrderDaoConfig.getIdentityScope().clear();
        shopOrderItemDaoConfig.getIdentityScope().clear();
        advertisingDaoConfig.getIdentityScope().clear();
        permissionDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
        gpsLocationDaoConfig.getIdentityScope().clear();
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

    public SystemDao getSystemDao() {
        return systemDao;
    }

    public BackupDao getBackupDao() {
        return backupDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public BankcardDao getBankcardDao() {
        return bankcardDao;
    }

    public CatalogDao getCatalogDao() {
        return catalogDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public RetailDao getRetailDao() {
        return retailDao;
    }

    public ReduceDao getReduceDao() {
        return reduceDao;
    }

    public AttributeDao getAttributeDao() {
        return attributeDao;
    }

    public AttributeValueDao getAttributeValueDao() {
        return attributeValueDao;
    }

    public ProductAttributeDao getProductAttributeDao() {
        return productAttributeDao;
    }

    public SaleOrderDao getSaleOrderDao() {
        return saleOrderDao;
    }

    public SaleOrderReduceDao getSaleOrderReduceDao() {
        return saleOrderReduceDao;
    }

    public SaleOrderItemDao getSaleOrderItemDao() {
        return saleOrderItemDao;
    }

    public SaleOrderItemAttributeValueDao getSaleOrderItemAttributeValueDao() {
        return saleOrderItemAttributeValueDao;
    }

    public SaleOrderItemReduceDao getSaleOrderItemReduceDao() {
        return saleOrderItemReduceDao;
    }

    public CartDao getCartDao() {
        return cartDao;
    }

    public CartItemDao getCartItemDao() {
        return cartItemDao;
    }

    public ShopOrderDao getShopOrderDao() {
        return shopOrderDao;
    }

    public ShopOrderItemDao getShopOrderItemDao() {
        return shopOrderItemDao;
    }

    public AdvertisingDao getAdvertisingDao() {
        return advertisingDao;
    }

    public PermissionDao getPermissionDao() {
        return permissionDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

    public GpsLocationDao getGpsLocationDao() {
        return gpsLocationDao;
    }

}
