package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GPS_LOCATION.
 */
public class GpsLocation {

    /** Not-null value. */
    private String latitude;
    /** Not-null value. */
    private String lontitude;
    /** Not-null value. */
    private String time;
    private String address;

    public GpsLocation() {
    }

    public GpsLocation(String latitude, String lontitude, String time, String address) {
        this.latitude = latitude;
        this.lontitude = lontitude;
        this.time = time;
        this.address = address;
    }

    /** Not-null value. */
    public String getLatitude() {
        return latitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /** Not-null value. */
    public String getLontitude() {
        return lontitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLontitude(String lontitude) {
        this.lontitude = lontitude;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

}
