package com.itertk.app.mpos.dbhelper;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.itertk.app.mpos.dbhelper.ProductAttribute;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PRODUCT_ATTRIBUTE.
*/
public class ProductAttributeDao extends AbstractDao<ProductAttribute, Long> {

    public static final String TABLENAME = "PRODUCT_ATTRIBUTE";

    /**
     * Properties of entity ProductAttribute.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ProductAttributeId = new Property(0, Long.class, "productAttributeId", true, "PRODUCT_ATTRIBUTE_ID");
        public final static Property ProductId = new Property(1, long.class, "productId", false, "PRODUCT_ID");
        public final static Property AttributeId = new Property(2, long.class, "attributeId", false, "ATTRIBUTE_ID");
    };

    private DaoSession daoSession;

    private Query<ProductAttribute> product_ProductAttributeListQuery;

    public ProductAttributeDao(DaoConfig config) {
        super(config);
    }
    
    public ProductAttributeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PRODUCT_ATTRIBUTE' (" + //
                "'PRODUCT_ATTRIBUTE_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: productAttributeId
                "'PRODUCT_ID' INTEGER NOT NULL ," + // 1: productId
                "'ATTRIBUTE_ID' INTEGER NOT NULL );"); // 2: attributeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PRODUCT_ATTRIBUTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ProductAttribute entity) {
        stmt.clearBindings();
 
        Long productAttributeId = entity.getProductAttributeId();
        if (productAttributeId != null) {
            stmt.bindLong(1, productAttributeId);
        }
        stmt.bindLong(2, entity.getProductId());
        stmt.bindLong(3, entity.getAttributeId());
    }

    @Override
    protected void attachEntity(ProductAttribute entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ProductAttribute readEntity(Cursor cursor, int offset) {
        ProductAttribute entity = new ProductAttribute( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // productAttributeId
            cursor.getLong(offset + 1), // productId
            cursor.getLong(offset + 2) // attributeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ProductAttribute entity, int offset) {
        entity.setProductAttributeId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProductId(cursor.getLong(offset + 1));
        entity.setAttributeId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ProductAttribute entity, long rowId) {
        entity.setProductAttributeId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ProductAttribute entity) {
        if(entity != null) {
            return entity.getProductAttributeId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "productAttributeList" to-many relationship of Product. */
    public List<ProductAttribute> _queryProduct_ProductAttributeList(long productId) {
        synchronized (this) {
            if (product_ProductAttributeListQuery == null) {
                QueryBuilder<ProductAttribute> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductId.eq(null));
                product_ProductAttributeListQuery = queryBuilder.build();
            }
        }
        Query<ProductAttribute> query = product_ProductAttributeListQuery.forCurrentThread();
        query.setParameter(0, productId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getProductDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAttributeDao().getAllColumns());
            builder.append(" FROM PRODUCT_ATTRIBUTE T");
            builder.append(" LEFT JOIN PRODUCT T0 ON T.'PRODUCT_ID'=T0.'ID'");
            builder.append(" LEFT JOIN ATTRIBUTE T1 ON T.'ATTRIBUTE_ID'=T1.'ATTRIBUTE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ProductAttribute loadCurrentDeep(Cursor cursor, boolean lock) {
        ProductAttribute entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
         if(product != null) {
            entity.setProduct(product);
        }
        offset += daoSession.getProductDao().getAllColumns().length;

        Attribute attribute = loadCurrentOther(daoSession.getAttributeDao(), cursor, offset);
         if(attribute != null) {
            entity.setAttribute(attribute);
        }

        return entity;    
    }

    public ProductAttribute loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ProductAttribute> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ProductAttribute> list = new ArrayList<ProductAttribute>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ProductAttribute> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ProductAttribute> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
