package com.itertk.app.mpos.dbhelper;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.itertk.app.mpos.dbhelper.SaleOrderReduce;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SALE_ORDER_REDUCE.
*/
public class SaleOrderReduceDao extends AbstractDao<SaleOrderReduce, Long> {

    public static final String TABLENAME = "SALE_ORDER_REDUCE";

    /**
     * Properties of entity SaleOrderReduce.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property SaleOrderReduceId = new Property(0, Long.class, "saleOrderReduceId", true, "SALE_ORDER_REDUCE_ID");
        public final static Property SaleOrderId = new Property(1, long.class, "saleOrderId", false, "SALE_ORDER_ID");
        public final static Property ReduceId = new Property(2, long.class, "reduceId", false, "REDUCE_ID");
    };

    private DaoSession daoSession;

    private Query<SaleOrderReduce> saleOrder_SaleOrderReduceListQuery;

    public SaleOrderReduceDao(DaoConfig config) {
        super(config);
    }
    
    public SaleOrderReduceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SALE_ORDER_REDUCE' (" + //
                "'SALE_ORDER_REDUCE_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: saleOrderReduceId
                "'SALE_ORDER_ID' INTEGER NOT NULL ," + // 1: saleOrderId
                "'REDUCE_ID' INTEGER NOT NULL );"); // 2: reduceId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SALE_ORDER_REDUCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SaleOrderReduce entity) {
        stmt.clearBindings();
 
        Long saleOrderReduceId = entity.getSaleOrderReduceId();
        if (saleOrderReduceId != null) {
            stmt.bindLong(1, saleOrderReduceId);
        }
        stmt.bindLong(2, entity.getSaleOrderId());
        stmt.bindLong(3, entity.getReduceId());
    }

    @Override
    protected void attachEntity(SaleOrderReduce entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SaleOrderReduce readEntity(Cursor cursor, int offset) {
        SaleOrderReduce entity = new SaleOrderReduce( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // saleOrderReduceId
            cursor.getLong(offset + 1), // saleOrderId
            cursor.getLong(offset + 2) // reduceId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SaleOrderReduce entity, int offset) {
        entity.setSaleOrderReduceId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSaleOrderId(cursor.getLong(offset + 1));
        entity.setReduceId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SaleOrderReduce entity, long rowId) {
        entity.setSaleOrderReduceId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SaleOrderReduce entity) {
        if(entity != null) {
            return entity.getSaleOrderReduceId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "saleOrderReduceList" to-many relationship of SaleOrder. */
    public List<SaleOrderReduce> _querySaleOrder_SaleOrderReduceList(long saleOrderId) {
        synchronized (this) {
            if (saleOrder_SaleOrderReduceListQuery == null) {
                QueryBuilder<SaleOrderReduce> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SaleOrderId.eq(null));
                saleOrder_SaleOrderReduceListQuery = queryBuilder.build();
            }
        }
        Query<SaleOrderReduce> query = saleOrder_SaleOrderReduceListQuery.forCurrentThread();
        query.setParameter(0, saleOrderId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaleOrderDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getReduceDao().getAllColumns());
            builder.append(" FROM SALE_ORDER_REDUCE T");
            builder.append(" LEFT JOIN SALE_ORDER T0 ON T.'SALE_ORDER_ID'=T0.'SALE_ORDER_ID'");
            builder.append(" LEFT JOIN REDUCE T1 ON T.'REDUCE_ID'=T1.'REDUCE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SaleOrderReduce loadCurrentDeep(Cursor cursor, boolean lock) {
        SaleOrderReduce entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaleOrder saleOrder = loadCurrentOther(daoSession.getSaleOrderDao(), cursor, offset);
         if(saleOrder != null) {
            entity.setSaleOrder(saleOrder);
        }
        offset += daoSession.getSaleOrderDao().getAllColumns().length;

        Reduce reduce = loadCurrentOther(daoSession.getReduceDao(), cursor, offset);
         if(reduce != null) {
            entity.setReduce(reduce);
        }

        return entity;    
    }

    public SaleOrderReduce loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SaleOrderReduce> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SaleOrderReduce> list = new ArrayList<SaleOrderReduce>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SaleOrderReduce> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SaleOrderReduce> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
