package com.itertk.app.mpos.dbhelper;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.itertk.app.mpos.dbhelper.SaleOrderItemAttributeValue;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SALE_ORDER_ITEM_ATTRIBUTE_VALUE.
*/
public class SaleOrderItemAttributeValueDao extends AbstractDao<SaleOrderItemAttributeValue, Long> {

    public static final String TABLENAME = "SALE_ORDER_ITEM_ATTRIBUTE_VALUE";

    /**
     * Properties of entity SaleOrderItemAttributeValue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property SaleOrderItemAttributeValueId = new Property(0, Long.class, "saleOrderItemAttributeValueId", true, "SALE_ORDER_ITEM_ATTRIBUTE_VALUE_ID");
        public final static Property SaleOrderItemId = new Property(1, long.class, "saleOrderItemId", false, "SALE_ORDER_ITEM_ID");
        public final static Property AttributeValueId = new Property(2, long.class, "attributeValueId", false, "ATTRIBUTE_VALUE_ID");
    };

    private DaoSession daoSession;

    private Query<SaleOrderItemAttributeValue> saleOrderItem_SaleOrderItemAttributeValueListQuery;

    public SaleOrderItemAttributeValueDao(DaoConfig config) {
        super(config);
    }
    
    public SaleOrderItemAttributeValueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SALE_ORDER_ITEM_ATTRIBUTE_VALUE' (" + //
                "'SALE_ORDER_ITEM_ATTRIBUTE_VALUE_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: saleOrderItemAttributeValueId
                "'SALE_ORDER_ITEM_ID' INTEGER NOT NULL ," + // 1: saleOrderItemId
                "'ATTRIBUTE_VALUE_ID' INTEGER NOT NULL );"); // 2: attributeValueId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SALE_ORDER_ITEM_ATTRIBUTE_VALUE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SaleOrderItemAttributeValue entity) {
        stmt.clearBindings();
 
        Long saleOrderItemAttributeValueId = entity.getSaleOrderItemAttributeValueId();
        if (saleOrderItemAttributeValueId != null) {
            stmt.bindLong(1, saleOrderItemAttributeValueId);
        }
        stmt.bindLong(2, entity.getSaleOrderItemId());
        stmt.bindLong(3, entity.getAttributeValueId());
    }

    @Override
    protected void attachEntity(SaleOrderItemAttributeValue entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SaleOrderItemAttributeValue readEntity(Cursor cursor, int offset) {
        SaleOrderItemAttributeValue entity = new SaleOrderItemAttributeValue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // saleOrderItemAttributeValueId
            cursor.getLong(offset + 1), // saleOrderItemId
            cursor.getLong(offset + 2) // attributeValueId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SaleOrderItemAttributeValue entity, int offset) {
        entity.setSaleOrderItemAttributeValueId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSaleOrderItemId(cursor.getLong(offset + 1));
        entity.setAttributeValueId(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SaleOrderItemAttributeValue entity, long rowId) {
        entity.setSaleOrderItemAttributeValueId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SaleOrderItemAttributeValue entity) {
        if(entity != null) {
            return entity.getSaleOrderItemAttributeValueId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "saleOrderItemAttributeValueList" to-many relationship of SaleOrderItem. */
    public List<SaleOrderItemAttributeValue> _querySaleOrderItem_SaleOrderItemAttributeValueList(long saleOrderItemId) {
        synchronized (this) {
            if (saleOrderItem_SaleOrderItemAttributeValueListQuery == null) {
                QueryBuilder<SaleOrderItemAttributeValue> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SaleOrderItemId.eq(null));
                saleOrderItem_SaleOrderItemAttributeValueListQuery = queryBuilder.build();
            }
        }
        Query<SaleOrderItemAttributeValue> query = saleOrderItem_SaleOrderItemAttributeValueListQuery.forCurrentThread();
        query.setParameter(0, saleOrderItemId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaleOrderItemDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAttributeValueDao().getAllColumns());
            builder.append(" FROM SALE_ORDER_ITEM_ATTRIBUTE_VALUE T");
            builder.append(" LEFT JOIN SALE_ORDER_ITEM T0 ON T.'SALE_ORDER_ITEM_ID'=T0.'SALE_ORDER_ITEM_ID'");
            builder.append(" LEFT JOIN ATTRIBUTE_VALUE T1 ON T.'ATTRIBUTE_VALUE_ID'=T1.'VALUE_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected SaleOrderItemAttributeValue loadCurrentDeep(Cursor cursor, boolean lock) {
        SaleOrderItemAttributeValue entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaleOrderItem saleOrderItem = loadCurrentOther(daoSession.getSaleOrderItemDao(), cursor, offset);
         if(saleOrderItem != null) {
            entity.setSaleOrderItem(saleOrderItem);
        }
        offset += daoSession.getSaleOrderItemDao().getAllColumns().length;

        AttributeValue attributeValue = loadCurrentOther(daoSession.getAttributeValueDao(), cursor, offset);
         if(attributeValue != null) {
            entity.setAttributeValue(attributeValue);
        }

        return entity;    
    }

    public SaleOrderItemAttributeValue loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<SaleOrderItemAttributeValue> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<SaleOrderItemAttributeValue> list = new ArrayList<SaleOrderItemAttributeValue>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<SaleOrderItemAttributeValue> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<SaleOrderItemAttributeValue> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
