package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SHOP.
 */
public class Shop {

    private Long shopId;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String addr;

    public Shop() {
    }

    public Shop(Long shopId) {
        this.shopId = shopId;
    }

    public Shop(Long shopId, String name, String addr) {
        this.shopId = shopId;
        this.name = name;
        this.addr = addr;
    }

    public Long getShopId() {
        return shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getAddr() {
        return addr;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddr(String addr) {
        this.addr = addr;
    }

}
