package com.itertk.app.mpos.dbhelper;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.itertk.app.mpos.dbhelper.ShopOrderItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SHOP_ORDER_ITEM.
*/
public class ShopOrderItemDao extends AbstractDao<ShopOrderItem, Long> {

    public static final String TABLENAME = "SHOP_ORDER_ITEM";

    /**
     * Properties of entity ShopOrderItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property ShopOrderId = new Property(1, long.class, "shopOrderId", false, "SHOP_ORDER_ID");
        public final static Property ProductId = new Property(2, long.class, "productId", false, "PRODUCT_ID");
        public final static Property TotalPrice = new Property(3, String.class, "totalPrice", false, "TOTAL_PRICE");
        public final static Property Quantity = new Property(4, long.class, "quantity", false, "QUANTITY");
        public final static Property Price = new Property(5, String.class, "price", false, "PRICE");
    };

    private DaoSession daoSession;

    private Query<ShopOrderItem> shopOrder_ShopOrderItemListQuery;

    public ShopOrderItemDao(DaoConfig config) {
        super(config);
    }
    
    public ShopOrderItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SHOP_ORDER_ITEM' (" + //
                "'_ID' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "'SHOP_ORDER_ID' INTEGER NOT NULL ," + // 1: shopOrderId
                "'PRODUCT_ID' INTEGER NOT NULL ," + // 2: productId
                "'TOTAL_PRICE' TEXT NOT NULL ," + // 3: totalPrice
                "'QUANTITY' INTEGER NOT NULL ," + // 4: quantity
                "'PRICE' TEXT NOT NULL );"); // 5: price
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SHOP_ORDER_ITEM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ShopOrderItem entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindLong(2, entity.getShopOrderId());
        stmt.bindLong(3, entity.getProductId());
        stmt.bindString(4, entity.getTotalPrice());
        stmt.bindLong(5, entity.getQuantity());
        stmt.bindString(6, entity.getPrice());
    }

    @Override
    protected void attachEntity(ShopOrderItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ShopOrderItem readEntity(Cursor cursor, int offset) {
        ShopOrderItem entity = new ShopOrderItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getLong(offset + 1), // shopOrderId
            cursor.getLong(offset + 2), // productId
            cursor.getString(offset + 3), // totalPrice
            cursor.getLong(offset + 4), // quantity
            cursor.getString(offset + 5) // price
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ShopOrderItem entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShopOrderId(cursor.getLong(offset + 1));
        entity.setProductId(cursor.getLong(offset + 2));
        entity.setTotalPrice(cursor.getString(offset + 3));
        entity.setQuantity(cursor.getLong(offset + 4));
        entity.setPrice(cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ShopOrderItem entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ShopOrderItem entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "shopOrderItemList" to-many relationship of ShopOrder. */
    public List<ShopOrderItem> _queryShopOrder_ShopOrderItemList(long shopOrderId) {
        synchronized (this) {
            if (shopOrder_ShopOrderItemListQuery == null) {
                QueryBuilder<ShopOrderItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ShopOrderId.eq(null));
                shopOrder_ShopOrderItemListQuery = queryBuilder.build();
            }
        }
        Query<ShopOrderItem> query = shopOrder_ShopOrderItemListQuery.forCurrentThread();
        query.setParameter(0, shopOrderId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getShopOrderDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProductDao().getAllColumns());
            builder.append(" FROM SHOP_ORDER_ITEM T");
            builder.append(" LEFT JOIN SHOP_ORDER T0 ON T.'SHOP_ORDER_ID'=T0.'ID'");
            builder.append(" LEFT JOIN PRODUCT T1 ON T.'PRODUCT_ID'=T1.'ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ShopOrderItem loadCurrentDeep(Cursor cursor, boolean lock) {
        ShopOrderItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ShopOrder shopOrder = loadCurrentOther(daoSession.getShopOrderDao(), cursor, offset);
         if(shopOrder != null) {
            entity.setShopOrder(shopOrder);
        }
        offset += daoSession.getShopOrderDao().getAllColumns().length;

        Product product = loadCurrentOther(daoSession.getProductDao(), cursor, offset);
         if(product != null) {
            entity.setProduct(product);
        }

        return entity;    
    }

    public ShopOrderItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ShopOrderItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ShopOrderItem> list = new ArrayList<ShopOrderItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ShopOrderItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ShopOrderItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
