package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYSTEM.
 */
public class System {

    private Long systemId;
    /** Not-null value. */
    private String soft_version;
    /** Not-null value. */
    private String hard_version;
    private long last_update;

    public System() {
    }

    public System(Long systemId) {
        this.systemId = systemId;
    }

    public System(Long systemId, String soft_version, String hard_version, long last_update) {
        this.systemId = systemId;
        this.soft_version = soft_version;
        this.hard_version = hard_version;
        this.last_update = last_update;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /** Not-null value. */
    public String getSoft_version() {
        return soft_version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSoft_version(String soft_version) {
        this.soft_version = soft_version;
    }

    /** Not-null value. */
    public String getHard_version() {
        return hard_version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHard_version(String hard_version) {
        this.hard_version = hard_version;
    }

    public long getLast_update() {
        return last_update;
    }

    public void setLast_update(long last_update) {
        this.last_update = last_update;
    }

}
