package com.itertk.app.mpos.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long clerkNo;
    /** Not-null value. */
    private String clerkName;
    /** Not-null value. */
    private String loginPwd;
    private String phone;
    private Long type;
    private String image_url;
    private Boolean remember_password;
    private java.util.Date last_login;
    private java.util.Date last_logout;

    public User() {
    }

    public User(Long clerkNo) {
        this.clerkNo = clerkNo;
    }

    public User(Long clerkNo, String clerkName, String loginPwd, String phone, Long type, String image_url, Boolean remember_password, java.util.Date last_login, java.util.Date last_logout) {
        this.clerkNo = clerkNo;
        this.clerkName = clerkName;
        this.loginPwd = loginPwd;
        this.phone = phone;
        this.type = type;
        this.image_url = image_url;
        this.remember_password = remember_password;
        this.last_login = last_login;
        this.last_logout = last_logout;
    }

    public Long getClerkNo() {
        return clerkNo;
    }

    public void setClerkNo(Long clerkNo) {
        this.clerkNo = clerkNo;
    }

    /** Not-null value. */
    public String getClerkName() {
        return clerkName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClerkName(String clerkName) {
        this.clerkName = clerkName;
    }

    /** Not-null value. */
    public String getLoginPwd() {
        return loginPwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Long getType() {
        return type;
    }

    public void setType(Long type) {
        this.type = type;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Boolean getRemember_password() {
        return remember_password;
    }

    public void setRemember_password(Boolean remember_password) {
        this.remember_password = remember_password;
    }

    public java.util.Date getLast_login() {
        return last_login;
    }

    public void setLast_login(java.util.Date last_login) {
        this.last_login = last_login;
    }

    public java.util.Date getLast_logout() {
        return last_logout;
    }

    public void setLast_logout(java.util.Date last_logout) {
        this.last_logout = last_logout;
    }

}
